/***********************************************************************
 AUROSANAX ERP DEMO
 Archivo: certificado.js
 Módulo: Certificados médicos por atención
 Versión: 1.0.0
 Fecha: 2026-08-12
 -----------------------------------------------------------------------
 ARQUITECTURA
 - Módulo funcional independiente.
 - Una fila por certificado emitido; una atención puede tener varios.
 - detalle_json conserva la fotografía documental de la emisión.
 - Diagnósticos solo se leen; NO se modifican.
 - Atención finalizada puede emitir/corregir certificados.
 - Solo bloquea atención anulada/cancelada/archivada.
 - PDF no se almacena: se reconstruye e imprime bajo demanda.
 - Responsive: escritorio, tablet, iPhone y Android.
************************************************************************/
(function(){
'use strict';
if(window.auroCertificados?.version) return;
const VERSION='1.0.0', JSON_VERSION='AUROSANAX_CERTIFICADO_JSON_V1';
const state={idAtencion:'',contexto:null,diagnosticos:[],certificados:[],editandoId:'',guardando:false,token:0};
const txt=v=>String(v??'').trim();
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const norm=v=>txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
function apiUrl(){try{if(typeof API_URL!=='undefined'&&API_URL)return txt(API_URL);}catch(e){} return txt(window.API_URL||document.getElementById('appsScriptUrl')?.value);}
async function get(accion,p={}){const b=apiUrl();if(!b)throw Error('API_URL no está definida.');const q=new URLSearchParams({accion,_:Date.now()});Object.entries(p).forEach(([k,v])=>{if(txt(v))q.append(k,v)});const r=await fetch(b+'?'+q,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
async function post(accion,data){const r=await fetch(apiUrl(),{method:'POST',body:JSON.stringify({accion,data})});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
function activa(){try{const a=window.getAtencionActiva?.();if(a?.id_atencion)return a;}catch(e){} try{const a=window.obtenerContextoAtencionActual?.();if(a?.id_atencion)return a;}catch(e){} return window.atencionesState?.atencionActual||window.currentAttention||window.atencionActual||null;}
function idActiva(){try{const x=txt(window.getIdAtencionActiva?.());if(x)return x;}catch(e){} const a=activa();return txt(a?.id_atencion||window.planState?.atencionActual||window.examenFisicoState?.atencionActual||window.auroDiagnosticosState?.atencionActual);}
function contexto(){const a=activa()||{},id=txt(a.id_atencion||idActiva()),estado=norm(a.estado_atencion||a.estado||a.estado_consulta);const bloqueada=/(anulad|cancelad|archivad)/.test(estado);return {id,atencion:a,bloqueada,editable:!!id&&!bloqueada,numeroConsulta:txt(a.numero_consulta||a.numero_atencion),idPaciente:txt(a.id_paciente),idHistoria:txt(a.id_historia),idMedico:txt(a.id_medico)};}
function arr(x){return Array.isArray(x)?x:Array.isArray(x?.registros)?x.registros:Array.isArray(x?.data)?x.data:[];}
function parse(v){if(v&&typeof v==='object')return v;try{return JSON.parse(txt(v)||'{}')}catch(e){return {}}}
function hoy(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function sumarDias(f,dias){const m=txt(f).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return '';const x=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));x.setUTCDate(x.getUTCDate()+Math.max(0,Number(dias||0)-1));return x.toISOString().slice(0,10);}
function fechaVisual(v){const m=txt(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:(txt(v)||'—');}
const UN=['CERO','UNO','DOS','TRES','CUATRO','CINCO','SEIS','SIETE','OCHO','NUEVE','DIEZ','ONCE','DOCE','TRECE','CATORCE','QUINCE','DIECISÉIS','DIECISIETE','DIECIOCHO','DIECINUEVE','VEINTE','VEINTIUNO','VEINTIDÓS','VEINTITRÉS','VEINTICUATRO','VEINTICINCO','VEINTISÉIS','VEINTISIETE','VEINTIOCHO','VEINTINUEVE','TREINTA'];
function numeroLetras(n){n=Number(n||0);if(n>=0&&n<=30)return UN[n];if(n<100){const d=['','','','TREINTA','CUARENTA','CINCUENTA','SESENTA','SETENTA','OCHENTA','NOVENTA'][Math.floor(n/10)];return n%10?d+' Y '+UN[n%10]:d;}return String(n);}
function fechaLetras(v){const m=txt(v).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return txt(v).toUpperCase();const meses=['','ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SEPTIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE'];return `${numeroLetras(+m[3])} DE ${meses[+m[2]]} DEL ${m[1]}`;}
function instalarCSS(){if(document.getElementById('auroCertCSS'))return;const s=document.createElement('style');s.id='auroCertCSS';s.textContent=`
#auroCertificadosApp{font-family:inherit;color:#1f2937}#auroCertificadosApp *{box-sizing:border-box}.ac-shell{display:grid;gap:16px}.ac-hero{padding:18px;border:1px solid #ead7e2;border-radius:20px;background:linear-gradient(135deg,#fff,#fff7fb);display:flex;justify-content:space-between;gap:14px;align-items:center}.ac-hero h3{margin:0;color:#6c1d52;font-weight:900}.ac-hero p{margin:4px 0 0;color:#6b7280}.ac-pill{padding:8px 11px;border-radius:999px;background:#fdf2f8;color:#8b1e5a;font-size:12px;font-weight:850}.ac-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(300px,.85fr);gap:16px}.ac-card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden}.ac-head{padding:13px 15px;background:#fafafa;border-bottom:1px solid #eee;font-weight:850}.ac-body{padding:15px}.ac-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ac-field.full{grid-column:1/-1}.ac-field label{display:block;font-size:12px;font-weight:800;color:#4b5563;margin-bottom:5px}.ac-field input,.ac-field select,.ac-field textarea{width:100%;border:1px solid #d1d5db;border-radius:12px;padding:10px 11px;font:inherit}.ac-field textarea{min-height:92px;resize:vertical}.ac-dx{display:grid;gap:7px}.ac-dx label{display:flex;gap:8px;padding:9px;border:1px solid #e5e7eb;border-radius:11px;background:#fafafa}.ac-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.ac-btn{border:0;border-radius:12px;padding:10px 14px;font-weight:850;cursor:pointer}.ac-primary{background:linear-gradient(135deg,#8b1e5a,#c23b83);color:#fff}.ac-soft{background:#fdf2f8;color:#8b1e5a;border:1px solid #fbcfe8}.ac-item{border:1px solid #e5e7eb;border-radius:13px;padding:11px;margin-bottom:8px}.ac-item:last-child{margin-bottom:0}.ac-item-top{display:flex;justify-content:space-between;gap:10px}.ac-meta{font-size:12px;color:#6b7280;margin-top:4px}.ac-empty{padding:20px;text-align:center;color:#6b7280;border:1px dashed #d1d5db;border-radius:12px}.ac-msg{padding:10px 12px;border-radius:12px;font-size:13px}.ac-ok{background:#ecfdf5;color:#166534}.ac-error{background:#fef2f2;color:#991b1b}.ac-warn{background:#fffbeb;color:#92400e}.ac-preview{margin-top:14px;overflow:auto;background:#f3f4f6;border-radius:16px;padding:12px}.ac-paper{width:210mm;min-height:297mm;background:#fff;margin:auto;padding:16mm 18mm;box-shadow:0 8px 28px rgba(0,0,0,.12);transform-origin:top center}.ac-paper h1{text-align:center;font-size:18px;margin:14px 0 22px}.ac-paper p{font-size:12.5px;line-height:1.65;text-align:justify}.ac-paper .ac-doc-head{display:flex;justify-content:space-between;gap:15px;border-bottom:2px solid #8b1e5a;padding-bottom:10px}.ac-paper .ac-brand{font-weight:900;color:#8b1e5a}.ac-paper .ac-sign{margin-top:34px;border-top:1px solid #777;padding-top:8px;width:70%;font-size:12px}.ac-table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}.ac-table td{border:1px solid #d1d5db;padding:7px;vertical-align:top}
@media(max-width:900px){.ac-grid{grid-template-columns:1fr}.ac-form{grid-template-columns:1fr}.ac-field.full{grid-column:auto}.ac-preview{padding:8px}.ac-paper{transform:scale(.78);margin-bottom:-65mm}}
@media(max-width:600px){.ac-hero{display:block;padding:14px}.ac-pill{display:inline-block;margin-top:10px}.ac-body{padding:12px}.ac-field input,.ac-field select,.ac-field textarea{font-size:16px}.ac-actions{display:grid;grid-template-columns:1fr}.ac-btn{min-height:46px}.ac-paper{transform:scale(.46);margin-left:50%;translate:-50% 0;margin-bottom:-160mm}.ac-preview{overflow:hidden}}
`;document.head.appendChild(s);}
function html(){return `<div class="ac-shell"><div class="ac-hero"><div><h3><i class="bi bi-file-earmark-medical"></i> Certificados</h3><p>Emisión documental vinculada a la atención seleccionada.</p></div><div class="ac-pill" id="acContexto">Sin atención</div></div><div id="acMsg"></div><div class="ac-grid"><div class="ac-card"><div class="ac-head">Emisión de certificado</div><div class="ac-body"><div class="ac-form">
<div class="ac-field"><label>Tipo de certificado</label><select id="acTipo"><option>Certificado médico</option><option>Certificado de asistencia por consulta</option><option>Certificado prequirúrgico</option></select></div>
<div class="ac-field"><label>Fecha de emisión</label><input id="acFecha" type="date"></div>
<div class="ac-field"><label>Días de reposo</label><input id="acDias" type="number" min="0" max="365" value="0"></div>
<div class="ac-field"><label>Tipo de contingencia</label><select id="acContingencia"><option value="">Seleccione...</option><option>Enfermedad general</option><option>Accidente común</option><option>Enfermedad profesional</option><option>Accidente de trabajo</option><option>Maternidad</option><option>Otra</option></select></div>
<div class="ac-field"><label>Reposo desde</label><input id="acDesde" type="date"></div><div class="ac-field"><label>Reposo hasta</label><input id="acHasta" type="date"></div>
<div class="ac-field full"><label>Diagnósticos de esta atención</label><div id="acDx" class="ac-dx"></div></div>
<div class="ac-field"><label>Número de contacto</label><input id="acContacto" inputmode="tel"></div><div class="ac-field"><label>Institución / Empresa</label><input id="acEmpresa"></div>
<div class="ac-field full"><label>Resumen clínico</label><textarea id="acResumen"></textarea></div><div class="ac-field"><label>Actividad laboral</label><input id="acActividad"></div><div class="ac-field"><label>Dirección de trabajo</label><input id="acDireccionTrabajo"></div>
<div class="ac-field full"><label>Observaciones / extensión de reposo</label><textarea id="acObservaciones"></textarea></div></div>
<div class="ac-actions"><button class="ac-btn ac-primary" id="acGuardar">Emitir / Guardar certificado</button><button class="ac-btn ac-soft" id="acVista">Vista previa</button><button class="ac-btn ac-soft" id="acImprimir">Imprimir / PDF</button><button class="ac-btn ac-soft" id="acNuevo">Nuevo certificado</button></div><div id="acPreview" class="ac-preview" style="display:none"></div></div></div>
<div class="ac-card"><div class="ac-head">Certificados emitidos</div><div class="ac-body" id="acHistorial"></div></div></div></div>`}
function mount(){instalarCSS();let p=document.getElementById('hc_certificados');if(!p)return null;let m=document.getElementById('auroCertificadosMount');if(!m){m=document.createElement('div');m.id='auroCertificadosMount';p.appendChild(m)}if(!document.getElementById('auroCertificadosApp')){m.innerHTML='<div id="auroCertificadosApp">'+html()+'</div>';eventos();}return m;}
function msg(t,s){const e=document.getElementById('acMsg');if(e)e.innerHTML=s?`<div class="ac-msg ac-${t}">${esc(s)}</div>`:'';}
function v(id){return txt(document.getElementById(id)?.value)} function sv(id,x){const e=document.getElementById(id);if(e)e.value=x??''}
function eventos(){document.getElementById('acDias')?.addEventListener('input',calcularHasta);document.getElementById('acDesde')?.addEventListener('change',calcularHasta);document.getElementById('acGuardar')?.addEventListener('click',guardar);document.getElementById('acVista')?.addEventListener('click',()=>vista(false));document.getElementById('acImprimir')?.addEventListener('click',()=>vista(true));document.getElementById('acNuevo')?.addEventListener('click',nuevo);}
function calcularHasta(){const d=Number(v('acDias')||0),f=v('acDesde')||v('acFecha')||hoy();if(d>0)sv('acHasta',sumarDias(f,d));else sv('acHasta','');}
async function cargarDx(id){try{const r=await get('listarDiagnosticosPorAtencion',{id_atencion:id});state.diagnosticos=arr(r);}catch(e){try{const r=await get('listarDiagnosticos');state.diagnosticos=arr(r).filter(x=>txt(x.id_atencion)===id)}catch(_){state.diagnosticos=[]}}renderDx();}
function renderDx(){const b=document.getElementById('acDx');if(!b)return;if(!state.diagnosticos.length){b.innerHTML='<div class="ac-empty">Sin diagnósticos registrados para esta atención.</div>';return;}b.innerHTML=state.diagnosticos.map((d,i)=>`<label><input type="checkbox" data-acdx="${i}" checked><span><b>${esc(d.codigo_cie10||d.codigo||'S/C')}</b> · ${esc(d.descripcion||d.diagnostico||'')}</span></label>`).join('');}
async function cargarHistorial(id){try{const r=await get('listarCertificadosPorAtencion',{id_atencion:id});state.certificados=arr(r);}catch(e){state.certificados=[]}renderHistorial();}
function renderHistorial(){const b=document.getElementById('acHistorial');if(!b)return;if(!state.certificados.length){b.innerHTML='<div class="ac-empty">No existen certificados emitidos para esta atención.</div>';return;}b.innerHTML=[...state.certificados].reverse().map(c=>{const d=parse(c.detalle_json);return `<div class="ac-item"><div class="ac-item-top"><div><b>${esc(c.tipo_certificado||d.tipo_certificado||'Certificado')}</b><div class="ac-meta">${esc(fechaVisual(c.fecha_emision||d.fecha_emision))} · ${esc(c.id_certificado)}</div></div><button class="ac-btn ac-soft" data-aceditar="${esc(c.id_certificado)}">Abrir</button></div></div>`}).join('');b.querySelectorAll('[data-aceditar]').forEach(x=>x.onclick=()=>abrir(x.dataset.aceditar));}
function dxSeleccionados(){return [...document.querySelectorAll('[data-acdx]:checked')].map(x=>state.diagnosticos[Number(x.dataset.acdx)]).filter(Boolean).map(d=>({id_diagnostico:txt(d.id_diagnostico),codigo_cie10:txt(d.codigo_cie10||d.codigo),descripcion:txt(d.descripcion||d.diagnostico),principal:d.principal===true||norm(d.principal)==='si',tipo_diagnostico:txt(d.tipo_diagnostico||d.tipo)}));}
function datos(){const c=state.contexto||contexto(),a=c.atencion||{},fecha=v('acFecha')||hoy(),dias=Number(v('acDias')||0),desde=v('acDesde')||(dias?fecha:''),hasta=v('acHasta')||(dias?sumarDias(desde,dias):'');const detalle={version:JSON_VERSION,tipo_certificado:v('acTipo'),fecha_emision:fecha,dias_reposo:dias,contingencia:v('acContingencia'),reposo_desde:desde,reposo_hasta:hasta,diagnosticos:dxSeleccionados(),contacto:v('acContacto'),institucion_empresa:v('acEmpresa'),resumen_clinico:v('acResumen'),actividad_laboral:v('acActividad'),direccion_trabajo:v('acDireccionTrabajo'),observaciones:v('acObservaciones')};return {id_certificado:state.editandoId||undefined,id_atencion:c.id,id_cita:txt(a.id_cita),numero_consulta:c.numeroConsulta,id_paciente:txt(a.id_paciente),nombre_paciente:txt(a.nombre_paciente||a.paciente_nombre),numero_documento:txt(a.numero_documento||a.cedula||a.identificacion),id_historia:txt(a.id_historia),id_medico:txt(a.id_medico),nombre_medico:txt(a.nombre_medico||a.medico_nombre||document.querySelector('.doctor-pill strong')?.textContent),especialidad:txt(a.especialidad||a.medico_especialidad),tipo_certificado:v('acTipo'),fecha_emision:fecha,detalle_json:JSON.stringify(detalle),estado:'Activo',version:VERSION};}
async function guardar(){if(state.guardando)return;const c=state.contexto||contexto();if(!c.id)return msg('warn','Seleccione una atención antes de emitir el certificado.');if(c.bloqueada)return msg('warn','La atención está anulada, cancelada o archivada.');const data=datos();if(!data.nombre_paciente)return msg('warn','No se pudo identificar al paciente de la atención.');state.guardando=true;const b=document.getElementById('acGuardar');if(b)b.disabled=true;try{const r=await post(state.editandoId?'editarCertificado':'guardarCertificado',data);if(r?.success===false)throw Error(r.message||'No se pudo guardar.');state.editandoId=txt(r.id||data.id_certificado);msg('ok','Certificado guardado correctamente.');await cargarHistorial(c.id);}catch(e){msg('error',e.message||'Error al guardar el certificado.')}finally{state.guardando=false;if(b)b.disabled=false}}
function abrir(id){const c=state.certificados.find(x=>txt(x.id_certificado)===txt(id));if(!c)return;const d=parse(c.detalle_json);state.editandoId=txt(c.id_certificado);sv('acTipo',c.tipo_certificado||d.tipo_certificado);sv('acFecha',c.fecha_emision||d.fecha_emision);sv('acDias',d.dias_reposo??0);sv('acContingencia',d.contingencia);sv('acDesde',d.reposo_desde);sv('acHasta',d.reposo_hasta);sv('acContacto',d.contacto);sv('acEmpresa',d.institucion_empresa);sv('acResumen',d.resumen_clinico);sv('acActividad',d.actividad_laboral);sv('acDireccionTrabajo',d.direccion_trabajo);sv('acObservaciones',d.observaciones);setTimeout(()=>{const cod=new Set((d.diagnosticos||[]).map(x=>txt(x.codigo_cie10)));document.querySelectorAll('[data-acdx]').forEach(x=>{const dx=state.diagnosticos[Number(x.dataset.acdx)];x.checked=cod.has(txt(dx?.codigo_cie10||dx?.codigo))})},0);msg('ok','Certificado cargado para revisión.');}
function nuevo(){state.editandoId='';['acContacto','acEmpresa','acResumen','acActividad','acDireccionTrabajo','acObservaciones'].forEach(x=>sv(x,''));sv('acTipo','Certificado médico');sv('acFecha',hoy());sv('acDias','0');sv('acContingencia','');sv('acDesde','');sv('acHasta','');document.querySelectorAll('[data-acdx]').forEach(x=>x.checked=true);document.getElementById('acPreview').style.display='none';msg('','');}
function docHTML(data){const d=parse(data.detalle_json),dx=d.diagnosticos||[],dias=Number(d.dias_reposo||0),pac=data.nombre_paciente||'Paciente',ced=data.numero_documento||'—',hc=data.id_historia||'—',med=data.nombre_medico||'Profesional tratante',esp=data.especialidad||'Medicina';return `<div class="ac-paper"><div class="ac-doc-head"><div><div class="ac-brand">AUROSANAX</div><small>Documento clínico emitido desde ERP</small></div><div style="text-align:right"><b>Guayaquil, ${esc(fechaVisual(d.fecha_emision))}</b><br><small>ID: ${esc(data.id_certificado||'BORRADOR')}</small></div></div><h1>${esc((data.tipo_certificado||d.tipo_certificado||'CERTIFICADO MÉDICO').toUpperCase())}</h1><p>Por medio del presente se certifica que el/la paciente <b>${esc(pac)}</b>, identificado/a con documento <b>${esc(ced)}</b>, historia clínica <b>${esc(hc)}</b>, fue atendido/a en esta institución dentro de la consulta <b>#${esc(data.numero_consulta||'—')}</b>.</p><table class="ac-table"><tr><td><b>Resumen clínico</b><br>${esc(d.resumen_clinico||'No especificado')}</td></tr><tr><td><b>Actividad laboral</b><br>${esc(d.actividad_laboral||'No especificada')}</td><td><b>Institución / Empresa</b><br>${esc(d.institucion_empresa||'No especificada')}</td></tr><tr><td><b>Contacto</b><br>${esc(d.contacto||'—')}</td><td><b>Contingencia</b><br>${esc(d.contingencia||'—')}</td></tr></table><p><b>Diagnóstico(s) CIE-10:</b><br>${dx.length?dx.map(x=>`${esc(x.codigo_cie10)} — ${esc(x.descripcion)}`).join('<br>'):'Sin diagnóstico seleccionado para el documento.'}</p>${dias>0?`<p>Se indica reposo por <b>${dias} (${esc(numeroLetras(dias))}) día(s)</b>, desde el <b>${esc(fechaLetras(d.reposo_desde))}</b> hasta el <b>${esc(fechaLetras(d.reposo_hasta))}</b>.</p>`:''}${d.observaciones?`<p><b>Observaciones:</b> ${esc(d.observaciones)}</p>`:''}<div class="ac-sign"><b>${esc(med)}</b><br>${esc(esp)}<br>Profesional responsable</div></div>`;}
function vista(imprimir){const data=datos(),htmlDoc=docHTML(data);const p=document.getElementById('acPreview');if(!imprimir){p.innerHTML=htmlDoc;p.style.display='block';p.scrollIntoView({behavior:'smooth',block:'start'});return;}const w=window.open('','_blank','width=1000,height=900');if(!w){msg('warn','Permita ventanas emergentes para imprimir el certificado.');return;}const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);w.document.write(`<!doctype html><html class="${ios?'auro-ios':''}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Certificado médico</title><style>@page{size:A4 portrait;margin:12mm 14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;margin:0}.ac-paper{width:100%;min-height:270mm;padding:4mm}.ac-doc-head{display:flex;justify-content:space-between;border-bottom:2px solid #8b1e5a;padding-bottom:8px}.ac-brand{font-size:20px;font-weight:900;color:#8b1e5a}h1{text-align:center;font-size:19px;margin:18px 0 24px}p{font-size:12.5px;line-height:1.65;text-align:justify}.ac-table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}.ac-table td{border:1px solid #bbb;padding:7px;vertical-align:top}.ac-sign{margin-top:35px;border-top:1px solid #777;padding-top:8px;width:68%;font-size:12px}@media print{html,body{width:210mm!important;min-height:297mm!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.ac-paper{page-break-inside:avoid!important}}</style></head><body>${htmlDoc}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),ios?450:180);}
async function inicializar(){mount();const token=++state.token,c=contexto();state.contexto=c;state.idAtencion=c.id;const badge=document.getElementById('acContexto');if(badge)badge.textContent=c.id?(c.numeroConsulta?'Consulta #'+c.numeroConsulta:'Atención seleccionada'):'Sin atención seleccionada';if(!c.id){state.diagnosticos=[];state.certificados=[];renderDx();renderHistorial();nuevo();return;}await Promise.all([cargarDx(c.id),cargarHistorial(c.id)]);if(token!==state.token)return;nuevo();}
window.auroCertificados={version:VERSION,inicializar,estado:state,vistaPrevia:()=>vista(false),imprimir:()=>vista(true)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();},{once:true});else mount();
})();
